name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main  # Deploy only when pushing to main branch
  workflow_dispatch:  # Allow manual deploys too

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

    - name: Deploy to Hostinger
      run: |
        echo "Deploying to Hostinger..."

        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -p ${{ secrets.HOSTINGER_SSH_PORT }} \
            ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} << 'EOF'

            cd /home/${{ secrets.HOSTINGER_SSH_USER }}/domains/dermacirclesph.com/public_html/reports

            echo "Pulling latest code..."
            git pull origin main

            echo "Running Composer Install..."
            COMPOSER_PROCESS_TIMEOUT=0 composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "Installing NPM dependencies..."
            npm install

            echo "Building assets..."
            npm run build

            echo "Running Migrations..."
            php artisan migrate --force

            echo "Seeding Database..."
            php artisan db:seed --force

            echo "Clearing Caches..."
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            echo "Optimizing Cache..."
            php artisan optimize
            php artisan config:cache
            php artisan route:cache

            echo "Ensuring Storage Symlink..."
            php artisan storage:link || true  # In case it's already linked

            echo "Deployment Complete Commander! 🫡🚀"
        EOF
