name: Rollback Deployment on Hostinger

on:
  workflow_dispatch:
    inputs:
      rollback_to:
        description: 'Git Commit Hash or Branch to Rollback To'
        required: true
        default: 'production'

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

    - name: Rollback Code on Hostinger
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOSTINGER_SSH_PORT }} ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} << 'EOF'
          cd /path/to/your/subdomain/public_html  # Update this path
          git fetch origin
          git checkout ${{ github.event.inputs.rollback_to }}
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run build
          php artisan migrate --force
          php artisan db:seed --force
          php artisan config:cache
          php artisan route:cache
        EOF
